apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinnts-grading
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinnts-grading
  template:
    metadata:
      labels:
        app: sinnts-grading
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: sinnts-grading
          image: dhannun/apps:grading-v1.0.0-47
          ports:
            - containerPort: 2024
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: grading-secrets
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: grading-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grading-secrets
                  key: DB_PASSWORD
            - name: JWT_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: grading-config
                  key: JWT_EXPIRY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: grading-secrets
                  key: JWT_SECRET_KEY
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: grading-config
                  key: PORT
            - name: REFRESH_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: grading-config
                  key: REFRESH_TOKEN_EXPIRY
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: 2024
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: 2024
            initialDelaySeconds: 30
            periodSeconds: 10
