apiVersion: v1
kind: Secret
metadata:
  name: grading-secrets
  namespace: staging
type: Opaque
data:
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMzQuMjAzLjEyLjE3ODoyNTI0L3Npbm50cy1ncmFkaW5n
  DB_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET_KEY: NDUyODQ4MkI0RDYyNTE2NTU0Njg1NzZENTk3MTMzNzQzNjc3Mzk3QTI0NDMyNjQ2Mjk0QTQwNEU2MzUyNjY1NTZBNTg2RTMyNzIzNDc1Mzc3ODIxNDEyNTQ0MkE0NzJENEI2MTUwNjQ1MzY3NTY2QjU5NzAzMzczMzY3NjM4Nw==
